spring.application.name=fidelizacionMS
server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3306/fidelizacion_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
